### ISSUE TITLE
Process exited with code 1 error

### ISSUE THREAD

**Issue by Mennaruuk** [keshavbhatt/plumber#5]
Getting this error with any YouTube URL. Tried running plumber with and without sudo, but to no avail.
```
Process exited with code 1
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/am/snap/plumber/28/.local/share/org.keshavnrj.ubuntu/Plumber/core/__main__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/am/snap/plumber/28/.local/share/org.keshavnrj.ubuntu/Plumber/core/youtube_dl/__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/am/snap/plumber/28/.local/share/org.keshavnrj.ubuntu/Plumber/core/youtube_dl/options.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/am/snap/plumber/28/.local/share/org.keshavnrj.ubuntu/Plumber/core/youtube_dl/downloader/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/am/snap/plumber/28/.local/share/org.keshavnrj.ubuntu/Plumber/core/youtube_dl/downloader/common.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/am/snap/plumber/28/.local/share/org.keshavnrj.ubuntu/Plumber/core/youtube_dl/compat.py", line 2359, in <module>
  File "/usr/lib/python3.6/http/server.py", line 619, in <module>
    class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
  File "/usr/lib/python3.6/http/server.py", line 827, in SimpleHTTPRequestHandler
    mimetypes.init() # try to read system mime.types
  File "/usr/lib/python3.6/mimetypes.py", line 355, in init
    db.read(file)
  File "/usr/lib/python3.6/mimetypes.py", line 204, in read
    with open(filename, encoding='utf-8') as fp:
PermissionError: [Errno 13] Permission denied: '/etc/httpd/conf/mime.types'
```

**Comment by keshavbhatt** [comment]
How you installed the app ?

**Comment by androidmessages** [comment]
Yes, it is installed.
![image](https://user-images.githubusercontent.com/52135169/98402272-0427ba00-2035-11eb-9e27-a0f16f31c9f3.png)

**Comment by keshavbhatt** [comment]
Using snap or by other means ?

**Comment by androidmessages** [comment]
Correct, through Snap on Manjaro (XFCE).

**Comment by keshavbhatt** [comment]
I will try to replicate the issue on my system in the morning. Thanks for reporting.

**Comment by androidmessages** [comment]
You're absolutely welcome!!! I should note that Snap on Manjaro and Arch Linux in general has been[ suffering from issues recently](https://forum.snapcraft.io/t/completely-broken-snapd-environment-in-manjaro-20-1-2/20900/6).

**Comment by keshavbhatt** [comment]
Sorry to tell you that this is a Manjaro specific issue, am not able to reproduce it on Ubuntu with the snap install.

**Comment by Mennaruuk** [comment]
You are correct. I tried it on Pop!_OS, and it works just fine. Don't know what's exactly wrong with Manjaro.
(BTW...kudos for making the program work on live-streamed YouTube videos as well, this program is a time-saver!)

**Comment by Mennaruuk** [comment]
Also, any love for Windows + Mac? I think combining the app and all its dependencies into one JAR app would make it much easier for all platforms, just like JDownloader 2. But if you have any better ideas, that'd be even better! Plumber is a seriously underutilized app with amazing potential, and I'm happy to see your developing and maintaining it!!!

**Comment by Foufoutos** [comment]
Hello, I get the same error the last days, mainly in twitter videos. Ubuntu 20.04, app installed via snap store

**Comment by keshavbhatt** [comment]
I will try to replicate the issue.
Thanks

**Comment by Foufoutos** [comment]
Today, after the latest ubuntu updates and a pc reboot, plumber is working fine

**Comment by keshavbhatt** [comment]
You should've recieved an update :)

**Comment by Foufoutos** [comment]
Yes, everything works fine. Thanks
